[build]
  command = "curl -sSL https://install.python-poetry.org | python3 - && pip install -r requirements.txt && gunicorn app:app"
  publish = "/"

[build.environment]
  PYTHON_VERSION = "3.11.8"
